[package]
name = "destructo-bot-3000"
version = "0.1.0"
authors = ["Calvin Brown <calvinb085@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlbot = "0.5.0"
na = "0.18.3"